import{u as N,r,j as e}from"../../context/WindowManagerContext.js";import{m as W}from"../../assets/proxy.js";import{c as d}from"../../assets/createLucideIcon.js";/**
 * @license lucide-react v0.522.0 - ISC
 *
 * This source code is licensed under the ISC license.
 * See the LICENSE file in the root directory of this source tree.
 */const k=[["path",{d:"M5 12h14",key:"1ays0h"}]],M=d("minus",k);/**
 * @license lucide-react v0.522.0 - ISC
 *
 * This source code is licensed under the ISC license.
 * See the LICENSE file in the root directory of this source tree.
 */const _=[["rect",{width:"18",height:"18",x:"3",y:"3",rx:"2",key:"afitv7"}]],E=d("square",_);/**
 * @license lucide-react v0.522.0 - ISC
 *
 * This source code is licensed under the ISC license.
 * See the LICENSE file in the root directory of this source tree.
 */const $=[["path",{d:"M18 6 6 18",key:"1bl5f8"}],["path",{d:"m6 6 12 12",key:"d8bk6v"}]],C=d("x",$),q=({windowData:c})=>{const{id:s,title:h,icon:l,content:x,isMinimized:w,isFocused:a,zIndex:m,defaultSize:t,defaultPos:n}=c,{closeWindow:p,minimizeWindow:b,focusWindow:f}=N();r.useRef(null);const[i,g]=r.useState(!1);r.useEffect(()=>{const o=()=>g(window.innerWidth<768);return o(),window.addEventListener("resize",o),()=>window.removeEventListener("resize",o)},[]);const u=i?"100%":(t==null?void 0:t.width)||600,v=i?"calc(100% - 40px)":(t==null?void 0:t.height)||400,y=i?0:(n==null?void 0:n.x)||(window.innerWidth-((t==null?void 0:t.width)||600))/2+(Math.random()*40-20),j=i?0:(n==null?void 0:n.y)||(window.innerHeight-((t==null?void 0:t.height)||400))/2+(Math.random()*40-20);return w?null:e.jsxs(W.div,{drag:!i,dragMomentum:!1,dragConstraints:{left:0,top:0,right:window.innerWidth-100,bottom:window.innerHeight-100},initial:{opacity:0,scale:.95,x:y,y:j},animate:{opacity:1,scale:1,x:i?0:void 0,y:i?0:void 0},exit:{opacity:0,scale:.95,y:window.innerHeight},transition:{type:"spring",damping:25,stiffness:300},onPointerDown:()=>f(s),style:{zIndex:m,width:u,height:v,position:"absolute",top:i?0:void 0,left:i?0:void 0},className:`flex flex-col rounded-t-lg overflow-hidden shadow-xp-window border-[3px] ${a?"border-xp-blue":"border-[#7a96df]"} bg-xp-bg`,children:[e.jsxs("div",{className:`h-8 flex items-center justify-between px-1 cursor-default select-none
          ${a?"bg-gradient-to-r from-xp-title-start via-xp-title-mid to-xp-title-end":"bg-gradient-to-r from-[#7a96df] to-[#9db9eb]"}`,children:[e.jsxs("div",{className:"flex items-center gap-1 overflow-hidden",children:[e.jsx("div",{className:"w-4 h-4 flex items-center justify-center text-white",children:l}),e.jsx("span",{className:"text-white font-tahoma font-bold text-sm truncate drop-shadow-[1px_1px_1px_rgba(0,0,0,0.5)]",children:h})]}),e.jsxs("div",{className:"flex items-center gap-[2px]",children:[e.jsx("button",{onClick:o=>{o.stopPropagation(),b(s)},className:"w-6 h-6 bg-[#136dff] hover:bg-[#3a93ff] active:bg-[#0054e3] rounded-[3px] border border-white/40 flex items-center justify-center text-white shadow-sm",children:e.jsx(M,{size:14,strokeWidth:3})}),e.jsx("button",{className:"w-6 h-6 bg-[#136dff] hover:bg-[#3a93ff] active:bg-[#0054e3] rounded-[3px] border border-white/40 flex items-center justify-center text-white shadow-sm opacity-50 cursor-not-allowed",children:e.jsx(E,{size:12,strokeWidth:3})}),e.jsx("button",{onClick:o=>{o.stopPropagation(),p(s)},className:"w-6 h-6 bg-[#e81123] hover:bg-[#f25056] active:bg-[#c90f1d] rounded-[3px] border border-white/40 flex items-center justify-center text-white shadow-sm",children:e.jsx(C,{size:16,strokeWidth:3})})]})]}),e.jsx("div",{className:"flex-1 bg-white overflow-hidden relative border-t border-white/50",children:x})]})};export{q as W,C as X};
